# A/B Testing: Advanced Practice

## In-Depth A/B Testing

## Load the Dataset and Perform a Brief Exploration

The data is stored in a file called **data/in_depth_ab_testing_lab/multipleChoiceResponses_cleaned.csv**. Feel free to check out the original dataset referenced at the bottom of this lab, although this cleaned version will undoubtedly be easier to work with. Additionally, meta-data regarding the questions is stored in a file name **data/in_depth_ab_testing_lab/schema.csv**. Load in the data itself as a Pandas DataFrame, and take a moment to briefly get acquainted with it.

> Note: If you can't get the file to load properly, try changing the encoding format as in `encoding='latin1'`

In [ ]:
#Your code here

## Wages and Education

You've been asked to determine whether education is impactful to salary. Develop a hypothesis test to compare the salaries of those with Master's degrees to those with Bachelor's degrees. Are the two statistically different according to your results?

> Note: The relevant features are stored in the 'FormalEducation' and 'AdjustedCompensation' features.

You may import the functions stored in the `the bootcamp_stats.py` file to help perform your hypothesis tests. It contains the stats functions that you previously coded: `welch_t(a,b)`, `welch_df(a, b)`, and `p_value(a, b, two_sided=False)`. 

Note that `scipy.stats.ttest_ind(a, b, equal_var=False)` performs a two-sided Welch's t-test and that p-values derived from two-sided tests are two times the p-values derived from one-sided tests. See the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html) for more information.

In [ ]:
#Your code here

## Wages and Education II

Now perform a similar statistical test comparing the AdjustedCompensation of those with Bachelor's degrees and those with Doctorates. If you haven't already, be sure to explore the distribution of the AdjustedCompensation feature for any anomalies.

In [ ]:
#Your code here

Median Values:
s1:74131.92
s2:38399.4
Sample sizes:
s1: 967
s2: 1107
Welch's t-test p-value: 0.1568238199472023


Repeated Test with Ouliers Removed:
Sample sizes:
s1: 964
s2: 1103
Welch's t-test p-value with outliers removed: 0.0

## Wages and Education III

Remember the multiple comparisons problem; rather than continuing on like this, perform an ANOVA test between the various 'FormalEducation' categories and their relation to 'AdjustedCompensation'.

In [ ]:
#Your code here

---

## Website A/B Testing

## Exploratory Analysis

Start by loading in the dataset stored in the file 'data/website_ab_testing_lab/homepage_actions.csv'. Then conduct an exploratory analysis to get familiar with the data.

> Hints:
    * Start investigating the id column:
        * How many viewers also clicked?
        * Are there any anomalies with the data; did anyone click who didn't view?
        * Is there any overlap between the control and experiment groups? 
            * If so, how do you plan to account for this in your experimental design?

In [ ]:
#Your code here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
%matplotlib inline

df = pd.read_csv('data/website_ab_testing_lab/homepage_actions.csv')
print(len(df), df.sample(20))

8188                        timestamp      id       group action
4087  2016-11-22 09:45:53.547508  315448     control   view
6844  2016-12-31 01:44:35.792238  371595  experiment   view
5956  2016-12-18 22:40:16.507761  681943     control   view
4603  2016-11-29 19:10:05.088879  573052     control  click
4223  2016-11-23 19:19:48.342949  843001     control  click
1715  2016-10-18 15:56:06.412086  187518     control   view
6127  2016-12-21 07:56:01.420839  547387     control   view
5596  2016-12-13 23:02:07.420589  304586  experiment   view
6784  2016-12-30 09:47:42.712422  677703     control   view
664   2016-10-03 23:32:11.782516  355306  experiment   view
7601  2017-01-10 08:51:25.161370  363077  experiment   view
5143  2016-12-07 11:21:20.225751  795200     control   view
322   2016-09-28 23:53:15.166027  230350     control   view
6309  2016-12-23 17:43:49.692753  840092  experiment   view
6852  2016-12-31 05:03:05.486330  770546  experiment   view
5952  2016-12-18 22:09:15.508341  692634     control  click
92    2016-09-25 20:51:30.731753  456084  experiment   view
2465  2016-10-30 00:54:10.108076  323922  experiment  click
1705  2016-10-18 14:06:33.644587  686398     control   view
4244  2016-11-24 00:40:03.654260  788612     control   view

In [ ]:
df.action.value_counts()

view     6328
click    1860
Name: action, dtype: int64

In [ ]:
cids = set(df[df.action=='click']['id'].unique())
vids = set(df[df.action=='view']['id'].unique())
print("Number of viewers: {} \tNumber of clickers: {}".format(len(vids), len(cids)))
print("Number of Viewers who didn't click: {}".format(len(vids-cids)))
print("Number of Clickers who didn't view: {}".format(len(cids-vids)))

Number of viewers: 6328 	Number of clickers: 1860
Number of Viewers who didn't click: 4468
Number of Clickers who didn't view: 0

In [ ]:
# Comment: Everyone who clicked, also viewed the homepage! 
# (Thank goodness!)

In [ ]:
eids = set(df[df.group=='experiment']['id'].unique())
cids = set(df[df.group=='control']['id'].unique())
print('Overlap of experiment and control groups: {}'.format(len(eids&cids)))

Overlap of experiment and control groups: 0

In [ ]:
# Comment: No overlap between the experiment and control groups.

## Conduct a Statistical Test

Conduct a statistical test to determine whether the experimental homepage was more effective than that of the control group.

In [ ]:
#Your code here
df['count'] = 1
df.head()

                    timestamp      id       group action  count
0  2016-09-24 17:42:27.839496  804196  experiment   view      1
1  2016-09-24 19:19:03.542569  434745  experiment   view      1
2  2016-09-24 19:36:00.944135  507599  experiment   view      1
3  2016-09-24 19:59:02.646620  671993     control   view      1
4  2016-09-24 20:26:14.466886  536734  experiment   view      1

In [ ]:
#Convert clicks into a binary variable on a user-by-user-basis
control = df[df.group=='control'].pivot(index='id', columns='action', values='count')
control = control.fillna(value=0)

experiment = df[df.group=='experiment'].pivot(index='id', columns='action', values='count')
experiment = experiment.fillna(value=0)



print("Sample sizes:\tControl: {}\tExperiment: {}".format(len(control), len(experiment)))
print("Total Clicks:\tControl: {}\tExperiment: {}".format(control.click.sum(), experiment.click.sum()))
print("Average click rate:\tControl: {}\tExperiment: {}".format(control.click.mean(), experiment.click.mean()))
control.head()

Sample sizes:	Control: 3332	Experiment: 2996
Total Clicks:	Control: 932.0	Experiment: 928.0
Average click rate:	Control: 0.2797118847539016	Experiment: 0.3097463284379172

action  click  view
id
182994    1.0   1.0
183089    0.0   1.0
183248    1.0   1.0
183515    0.0   1.0
183524    0.0   1.0

In [ ]:
import the bootcamp_stats as fs

In [ ]:
fs.p_value_welch_ttest(control.click, experiment.click)

0.004466402814337078

## Verifying Results

One sensible formulation of the data to answer the hypothesis test above would be to create a binary variable representing each individual in the experiment and control group. This binary variable would represent whether or not that individual clicked on the homepage; 1 for they did and 0 if they did not. 

The variance for the number of successes in a sample of a binomial variable with n observations is given by:

## $n\bullet p (1-p)$

Given this, perform 3 steps to verify the results of your statistical test:
1. Calculate the expected number of clicks for the experiment group, if it had the same click-through rate as that of the control group. 
2. Calculate the number of standard deviations that the actual number of clicks was from this estimate. 
3. Finally, calculate a p-value using the normal distribution based on this z-score.

### Step 1:
Calculate the expected number of clicks for the experiment group, if it had the same click-through rate as that of the control group.

In [ ]:
#Your code here|
control_rate = control.click.mean()
expected_experiment_clicks_under_null = control_rate * len(experiment)
print(expected_experiment_clicks_under_null)

838.0168067226891

### Step 2:
Calculate the number of standard deviations that the actual number of clicks was from this estimate.

In [ ]:
#Your code here
n = len(experiment)
p = control_rate
var = n * p * (1-p)
std = np.sqrt(var)
print(std)

24.568547907005815

In [ ]:

actual_experiment_clicks = experiment.click.sum()
z_score = (actual_experiment_clicks - expected_experiment_clicks_under_null)/std
print(z_score)

3.6625360854823588

### Step 3: 
Finally, calculate a p-value using the normal distribution based on this z-score.

In [ ]:
#Your code here
import scipy.stats as stats
p_val = stats.norm.sf(z_score) #or 1 - stats.norm.cdf(z_score)
print(p_val)

0.00012486528006951198

### Analysis:

Does this result roughly match that of the previous statistical test?

> Comment: **Your analysis here**

In [ ]:
# Comment: Yes, while the p-value is slightly lower, 
# both would lead to confident rejection of the null hypothesis. 
# The experimental page appears to be a more effective design.